services:
  - type: web
    name: henry-agent19v
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_NAME
        value: Henry Agent19v
      - key: BOT_OWNER_NAME
        value: Henrydev.ke
      - key: OWNER_NUMBER
        value: 254775351698
      - key: PREFIX
        value: "!"
      - key: BOT_MODE
        value: public
      - key: TZ
        value: Africa/Nairobi
      - key: PORT
        value: 3000
