"use strict";
/**
 * baileys-antiban patch command
 *
 * Patches an installed Baileys package to wrap makeWASocket with antiban middleware.
 * Designed for frameworks (OpenClaw, etc.) that create the socket internally and
 * don't expose a socket:ready hook.
 *
 * Idempotent: safe to re-run after plugin updates. Keeps a .antiban-backup file.
 *
 * Usage:
 *   npx baileys-antiban patch [--path <baileys-dir>] [--dry-run] [--preset conservative|moderate|aggressive]
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.applyPatch = applyPatch;
exports.unpatchFile = unpatchFile;
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));
const PATCH_MARKER_START = '// [BAILEYS-ANTIBAN-PATCH-START]';
const PATCH_MARKER_END = '// [BAILEYS-ANTIBAN-PATCH-END]';
function findBaileysDir(candidates) {
    for (const candidate of candidates) {
        if (!candidate)
            continue;
        const pkgPath = path.join(candidate, 'package.json');
        if (fs.existsSync(pkgPath)) {
            try {
                const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
                if (pkg.name === 'baileys' || pkg.name === '@whiskeysockets/baileys' || pkg.name === '@oxidezap/baileyrs') {
                    return path.resolve(candidate);
                }
            }
            catch {
                // not a valid package.json, skip
            }
        }
    }
    return null;
}
function findMakeWASocketFile(baileyDir) {
    // Ordered by likelihood of containing the actual makeWASocket definition
    const candidates = [
        'lib/socket/index.js',
        'lib/index.js',
        'lib/socket.js',
        'src/socket/index.js',
        'dist/socket/index.js',
        'dist/index.js',
    ];
    for (const rel of candidates) {
        const full = path.join(baileyDir, rel);
        if (!fs.existsSync(full))
            continue;
        const source = fs.readFileSync(full, 'utf-8');
        // Look for makeWASocket being defined (not just re-exported via export *)
        if (source.includes('function makeWASocket') ||
            source.includes('const makeWASocket') ||
            source.includes('exports.makeWASocket') ||
            source.includes('makeWASocket =')) {
            const isEsm = source.includes('export function makeWASocket') ||
                source.includes('export const makeWASocket') ||
                source.includes('export {') ||
                source.includes('export default');
            return { file: full, format: isEsm ? 'esm' : 'cjs' };
        }
    }
    // Fallback: search lib/ directory for the defining file
    const libDir = path.join(baileyDir, 'lib');
    if (fs.existsSync(libDir)) {
        const jsFiles = fs
            .readdirSync(libDir, { recursive: true })
            .filter((f) => typeof f === 'string' && f.endsWith('.js'))
            .map((f) => path.join(libDir, f));
        for (const full of jsFiles) {
            try {
                const source = fs.readFileSync(full, 'utf-8');
                if (source.includes('function makeWASocket') && source.includes('makeWASocket')) {
                    const isEsm = source.includes('export');
                    return { file: full, format: isEsm ? 'esm' : 'cjs' };
                }
            }
            catch {
                // skip unreadable files
            }
        }
    }
    return null;
}
function buildCjsPatch(opts) {
    return `
${PATCH_MARKER_START}
// Auto-generated by baileys-antiban patch. Re-run after Baileys/plugin updates.
(function() {
  try {
    const { wrapSocket } = require('baileys-antiban');
    const _orig = module.exports.makeWASocket;
    if (typeof _orig === 'function') {
      module.exports.makeWASocket = function(...args) {
        return wrapSocket(_orig.apply(this, args), {
          preset: process.env.ANTIBAN_PRESET || '${opts.preset}',
          delayBetweenMessages: {
            min: parseInt(process.env.ANTIBAN_MIN_DELAY || '${opts.minDelay}'),
            max: parseInt(process.env.ANTIBAN_MAX_DELAY || '${opts.maxDelay}'),
          },
          typingIndicator: (process.env.ANTIBAN_TYPING || '${opts.typing}') !== 'false',
        });
      };
    }
  } catch(e) {
    console.warn('[baileys-antiban] patch inactive:', e.message);
  }
})();
${PATCH_MARKER_END}
`;
}
function buildEsmPatch(source, opts) {
    // Strategy A: function declaration — rename and re-export wrapped version
    if (source.includes('export function makeWASocket')) {
        const patched = source.replace(/export function makeWASocket\b/, 'function _antiban_makeWASocket_orig');
        return (patched +
            `
${PATCH_MARKER_START}
// Auto-generated by baileys-antiban patch. Re-run after Baileys/plugin updates.
import { wrapSocket as _antibanWrap } from 'baileys-antiban';
export const makeWASocket = (...args) => _antibanWrap(_antiban_makeWASocket_orig(...args), {
  preset: process.env.ANTIBAN_PRESET || '${opts.preset}',
  delayBetweenMessages: {
    min: parseInt(process.env.ANTIBAN_MIN_DELAY || '${opts.minDelay}'),
    max: parseInt(process.env.ANTIBAN_MAX_DELAY || '${opts.maxDelay}'),
  },
  typingIndicator: (process.env.ANTIBAN_TYPING || '${opts.typing}') !== 'false',
});
${PATCH_MARKER_END}
`);
    }
    // Strategy B: const/let declaration — rename and re-export
    if (source.match(/export\s+(const|let)\s+makeWASocket\s*=/)) {
        const patched = source.replace(/export\s+(const|let)\s+makeWASocket\s*=/, 'const _antiban_makeWASocket_orig =');
        return (patched +
            `
${PATCH_MARKER_START}
// Auto-generated by baileys-antiban patch. Re-run after Baileys/plugin updates.
import { wrapSocket as _antibanWrap } from 'baileys-antiban';
export const makeWASocket = (...args) => _antibanWrap(_antiban_makeWASocket_orig(...args), {
  preset: process.env.ANTIBAN_PRESET || '${opts.preset}',
  delayBetweenMessages: {
    min: parseInt(process.env.ANTIBAN_MIN_DELAY || '${opts.minDelay}'),
    max: parseInt(process.env.ANTIBAN_MAX_DELAY || '${opts.maxDelay}'),
  },
  typingIndicator: (process.env.ANTIBAN_TYPING || '${opts.typing}') !== 'false',
});
${PATCH_MARKER_END}
`);
    }
    // Strategy C: named re-export — intercept at this boundary
    if (source.includes('makeWASocket')) {
        // Append import + re-export override at end of file
        return (source +
            `
${PATCH_MARKER_START}
// Auto-generated by baileys-antiban patch. Re-run after Baileys/plugin updates.
// NOTE: Strategy C (named export intercept) — less precise than A/B.
// If this breaks, use --path to target the file where makeWASocket is defined.
import { wrapSocket as _antibanWrap } from 'baileys-antiban';
const _antiban_raw = makeWASocket;
export { makeWASocket };  // shadowed below if engine supports block-level export rebind
// Fallback: log advisory if strategy C can't reassign
if (typeof makeWASocket === 'function') {
  // eslint-disable-next-line no-global-assign
  try { makeWASocket = (...a) => _antibanWrap(_antiban_raw(...a), { preset: '${opts.preset}', delayBetweenMessages: { min: ${opts.minDelay}, max: ${opts.maxDelay} }, typingIndicator: ${opts.typing} }); } catch {}
}
${PATCH_MARKER_END}
`);
    }
    throw new Error('Could not locate makeWASocket in this file. Try --path to a different Baileys file.');
}
function applyPatch(opts) {
    const { preset = 'conservative', minDelay = 1500, maxDelay = 4000, typingIndicator = true, dryRun = false, } = opts;
    // 1. Locate Baileys
    const defaultSearchPaths = [
        // OC-style nested location
        './node_modules/@openclaw/whatsapp/node_modules/baileys',
        './node_modules/@openclaw/whatsapp/node_modules/@whiskeysockets/baileys',
        // Standard locations
        './node_modules/baileys',
        './node_modules/@whiskeysockets/baileys',
        // Walk up
        '../node_modules/baileys',
        '../../node_modules/baileys',
    ];
    const searchPaths = opts.baileysPaths?.length ? opts.baileysPaths : defaultSearchPaths;
    const baileyDir = findBaileysDir(searchPaths);
    if (!baileyDir) {
        return {
            success: false,
            baileyDir: '(not found)',
            targetFile: '(not found)',
            alreadyPatched: false,
            format: 'cjs',
            message: 'Could not find Baileys package. Use --path <dir> to specify its location.\n' +
                'Example: npx baileys-antiban patch --path ./node_modules/@openclaw/whatsapp/node_modules/baileys',
        };
    }
    // 2. Find file containing makeWASocket
    const found = findMakeWASocketFile(baileyDir);
    if (!found) {
        return {
            success: false,
            baileyDir,
            targetFile: '(not found)',
            alreadyPatched: false,
            format: 'cjs',
            message: `Found Baileys at ${baileyDir} but could not locate makeWASocket definition.\n` +
                'The package structure may have changed. Please open an issue.',
        };
    }
    const { file: targetFile, format } = found;
    const source = fs.readFileSync(targetFile, 'utf-8');
    // 3. Check idempotency
    if (source.includes(PATCH_MARKER_START)) {
        return {
            success: true,
            baileyDir,
            targetFile,
            alreadyPatched: true,
            format,
            message: `Already patched: ${targetFile}\nRe-run with --force to re-apply.`,
        };
    }
    if (dryRun) {
        return {
            success: true,
            baileyDir,
            targetFile,
            alreadyPatched: false,
            format,
            message: `[dry-run] Would patch ${targetFile} (format: ${format})`,
        };
    }
    // 4. Backup
    const backupPath = targetFile + '.antiban-backup';
    if (!fs.existsSync(backupPath)) {
        fs.copyFileSync(targetFile, backupPath);
    }
    // 5. Build and apply patch
    const patchOpts = { preset, minDelay, maxDelay, typing: typingIndicator };
    let patched;
    try {
        if (format === 'cjs') {
            patched = source + buildCjsPatch(patchOpts);
        }
        else {
            patched = buildEsmPatch(source, patchOpts);
        }
    }
    catch (e) {
        return {
            success: false,
            baileyDir,
            targetFile,
            alreadyPatched: false,
            format,
            message: `Patch generation failed: ${e.message}`,
        };
    }
    fs.writeFileSync(targetFile, patched, 'utf-8');
    return {
        success: true,
        baileyDir,
        targetFile,
        alreadyPatched: false,
        format,
        backupPath,
        message: `✅ Patched: ${targetFile}\n` +
            `   Format:  ${format}\n` +
            `   Backup:  ${backupPath}\n` +
            `   Preset:  ${preset} (${minDelay}–${maxDelay}ms delays, typing=${typingIndicator})\n` +
            `\nTo auto-re-patch after plugin updates, add to your package.json:\n` +
            `  "scripts": { "postinstall": "npx baileys-antiban patch" }\n\n` +
            `Env overrides: ANTIBAN_PRESET, ANTIBAN_MIN_DELAY, ANTIBAN_MAX_DELAY, ANTIBAN_TYPING`,
    };
}
function unpatchFile(targetFile) {
    if (!fs.existsSync(targetFile)) {
        return { success: false, message: `File not found: ${targetFile}` };
    }
    const backupPath = targetFile + '.antiban-backup';
    if (!fs.existsSync(backupPath)) {
        // Try removing the patch block from source
        const source = fs.readFileSync(targetFile, 'utf-8');
        if (!source.includes(PATCH_MARKER_START)) {
            return { success: true, message: 'File is not patched.' };
        }
        const startIdx = source.indexOf(PATCH_MARKER_START);
        const endIdx = source.indexOf(PATCH_MARKER_END);
        if (startIdx === -1 || endIdx === -1) {
            return { success: false, message: 'Patch markers found but malformed. Restore manually from backup.' };
        }
        const cleaned = source.slice(0, startIdx) + source.slice(endIdx + PATCH_MARKER_END.length);
        fs.writeFileSync(targetFile, cleaned, 'utf-8');
        return { success: true, message: `Patch removed from ${targetFile}` };
    }
    fs.copyFileSync(backupPath, targetFile);
    fs.unlinkSync(backupPath);
    return { success: true, message: `Restored from backup: ${backupPath}` };
}
